<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Quotation Generated</title>
</head>

<body style="width: 100%!important;margin: 0;padding: 0;background-color: #F8F8F8;">
    <table border="0" cellpadding="0" cellspacing="0" style="padding: 10px 0;width: 600px;margin: 0 auto;">
        <tr>
            <td>
                <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;background-color: #FFF; padding: 20px">
                    <tr>
                        <td style="padding: 10px;text-align: center;color: #32C1CE;font-size: 20px;letter-spacing: 1px;font-family: Open Sans,Helvetica,Arial,sans-serif;">Hello, {company}
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 10px 0; text-align: left;color: #555; font-size: 13px;line-height: 24px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif;">
                            Your quotation has been generated by {site_name}.
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 3px; text-align: right;color: #555; font-size: 13px;line-height: 20px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif;"># : QTN-{invoice_number}</td>
                    </tr>
                    <tr>
                        <td style="padding: 3px; text-align: right;color: #555; font-size: 13px;line-height: 20px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif;">Created Date : {created_date}</td>
                    </tr>
                    <tr>
                        <td style="padding: 3px; text-align: right;color: #555; font-size: 13px;line-height: 20px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif;">Expiry Date : {expiry_date}</td>
                    </tr>
                    <tr>
                        <td style="padding: 3px 3px 15px 3px; text-align: right;color: #555; font-size: 13px;line-height: 20px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif;">Pamyent Method : {payment_method}</td>
                    </tr>
                    <tr>
                        <td>
                            <table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
                                <tr>
                                    <td style="width: 60%;padding: 3px 10px; text-align: right;color: #555; font-size: 13px;line-height: 24px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif; border: 1px solid #eee">Amount</td>
                                    <td style="width: 40%;padding: 3px 10px; text-align: left; font-weight: 600;color: #333; font-size: 13px;line-height: 24px;letter-spacing: .5px;font-family: Open Sans,Helvetica,Arial,sans-serif; border: 1px solid #eee">{abbr} {amount}</td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; text-align: center;color: #555; font-size: 13px;letter-spacing: .5px; line-height: 24px;font-family: Open Sans,Helvetica,Arial,sans-serif;">{customer_note}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; text-align: center;color: #555; font-size: 13px;letter-spacing: .5px; line-height: 24px;font-family: Open Sans,Helvetica,Arial,sans-serif;">
                            We have attached quotation pdf with this mail. Login now your account to view or download Quotes.
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 20px;text-align: center;font-family: Open Sans,Helvetica,Arial,sans-serif;">
                            <a href="{site_link}login" style="padding: 15px 20px; font-size: 14px;color: #FFF;letter-spacing: 1px; background-color:#32C1CE;text-decoration: none;border-radius: 4px;font-family: Open Sans,Helvetica,Arial,sans-serif;" target="_blank">View Quote</a>
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; text-align: center;color: #555; font-size: 13px;letter-spacing: .5px; line-height: 24px;font-family: Open Sans,Helvetica,Arial,sans-serif;">{terms_condition}</td>
                    </tr>
               </table>
               <table border="0" cellpadding="0" cellspacing="0" style="width: 600px; margin: 0 auto;">
                <tr>
                    <td style="text-align: center;font-size:12px;padding: 10px;color: #333;font-family: Open Sans,Helvetica,Arial,sans-serif;">
                        *** This is an automatically generated email – please do not reply to it. If you have any queries, please visit our website.' ***
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

</body>

</html>